# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postTask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='skills',
        ),
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
